import Navbar from "@/components/Navbar";

export default function PrivacyPolicy() {
  return (
    <div className="">
      <div className=" ">
        <Navbar />
        <div className="mx-[30px] sm:mx-[120px] my-8 text-gray-700">
          <h1 className="text-3xl font-bold my-8">Privacy Policy</h1>
          
          <h2 className="text-xl font-semibold my-4">Introduction</h2>
          <p>
            Welcome to Writesonic, Inc. (“us”, “we”, or “our”) operates https://writesonic.com 
            (hereinafter referred to as “Service”).
          </p>

          <p>
            Our Privacy Policy governs your visit to https://writesonic.com, and explains how 
            we collect, safeguard and disclose information that results from your use of our 
            Service.
          </p>

          <p>
            By using Service, you agree to the collection and use of information in accordance 
            with this policy. Unless otherwise defined in this Privacy Policy, the terms used 
            in this Privacy Policy have the same meanings as in our Terms and Conditions.
          </p>

          <h2 className="text-xl font-semibold my-4">Definitions</h2>
          <p><strong>Service</strong> means the https://writesonic.com website operated by Writesonic, Inc.</p>
          <p><strong>Personal Data</strong> means data about a living individual who can be identified 
          from those data (or from those and other information either in our possession or likely 
          to come into our possession).</p>
          <p><strong>Usage Data</strong> is data collected automatically either generated by the use of 
          Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
          <p><strong>Cookies</strong> are small files stored on your device (computer or mobile device).</p>
          <p><strong>Data Controller</strong> means a natural or legal person who determines the purposes 
          for which and the manner in which any personal data are, or are to be, processed.</p>

          <h2 className="text-xl font-semibold my-4">Information Collection and Use</h2>
          <p>
            We collect several different types of information for various purposes to provide and improve our Service to you.
          </p>

          <h2 className="text-xl font-semibold my-4">Types of Data Collected</h2>
          <p><strong>Personal Data</strong></p>
          <p>
            While using our Service, we may ask you to provide us with certain personally identifiable 
            information that can be used to contact or identify you (“Personal Data”). Personally 
            identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc ml-6">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Cookies and Usage Data</li>
          </ul>
          <p>
            We may use your Personal Data to contact you with newsletters, marketing or promotional 
            materials and other information that may be of interest to you. You may opt out of 
            receiving any, or all, of these communications from us by following the unsubscribe link 
            or by emailing us at support@writesonic.com.
          </p>

          <h2 className="text-xl font-semibold my-4">Retention of Data</h2>
          <p>
            We will retain your Personal Data only for as long as is necessary for the purposes set 
            out in this Privacy Policy. We will retain and use your Personal Data to the extent 
            necessary to comply with our legal obligations (for example, if we are required to retain 
            your data to comply with applicable laws), resolve disputes, and enforce our legal 
            agreements and policies.
          </p>

          {/* You can continue adding other sections of the privacy policy in a similar way */}
          
        </div>
      </div>
    </div>
  );
}
